# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: all
  connection: local
  gather_facts: yes
  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - apolloclark.nano-highlighting

    - geerlingguy.apache
    - apolloclark.apache-modsecurity

    - apolloclark.mysql
    - apolloclark.mysql-mcafee-audit
    # - apolloclark.mysql-deploy

    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.java
